version: '3.6'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: locamoto
      POSTGRES_DB: locamoto
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  mongoDB:
    image: mongo
    ports:
        - 27017:27017

  minio:
    image: minio/minio    
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
      - s3_config:/root/.minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: QezwmWmdCeSf6V583fV3
      MINIO_SECRET_KEY: 2VNtKZJxiwe8fH31iMFbrsttOrqgaKdePs0eWeAh
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ABC123456

volumes:  
  s3_data:
  s3_config:
  postgres: 